name: Docker Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: docker login
        env:
          DOCKER_USER: izelgurbuz   
          DOCKER_PASSWORD: izel12345       
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: docker build
        run: |
          docker build . -t izelgurbuz/perfanalytics
      
      - name: docker push
        run: |
          docker push izelgurbuz/perfanalytics
